### ISSUE TITLE
Update README.md with index of contents

### ISSUE THREAD

**Issue by tanaytoshniwal** [tanaytoshniwal/Data-Structures-Algorithms#1]
Create an index page in README.md for all the contents of the Repository

**Comment by nkhandelwal07** [comment]
It seems like an index already exists... What needs to be added?

**Comment by ayushanand09** [comment]
Hi Tanay,

I can help you in **"Creating an index page in README.md"** for all the contents of this repository.

I have also made a project on **"Command Line Music Player"**, (you can check it out on my profile). Please feel free to verify the "_README_ _file_" of that repository to  check the quality as will. 

Thanks,
Ayush
