### ISSUE TITLE
Implementation of Algorithms in all Programming Languages!

### ISSUE THREAD

**Issue by tanaytoshniwal** [tanaytoshniwal/Data-Structures-Algorithms#2]
Currently, there's only limited implementation in a few Programming Languages, i.e., C/C++, Java, and Python3!

**Comment by AntrikshSharma** [comment]
I would like to contribute :)

**Comment by tanaytoshniwal** [comment]
@AntrikshSharma Go ahead and raise a PR for the contribution you want to make! make sure to update the README.md as well!

**Comment by nkhandelwal07** [comment]
I made a PR for this. I'm not sure if it needs to be assigned first, so if so please assign me!

**Comment by tanaytoshniwal** [comment]
No, this is not a specific task, because there are a lot of programs that needs to be implemented, thus can't be addressed in a single issue!
Regarding the PR, I've added some comments, kindly check it!
Thanks

**Comment by Pratigyavlog** [comment]
I would like to contribute

**Comment by Nidita** [comment]
After reading the previous comments I could understand that it needs not to be assigned first, I have made a pull request recently.

**Comment by ayushanand09** [comment]
Hey @tanaytoshniwal ,

You just have accepted my pr. But under pull request section, it is not having  any kind of **_"hacktoberfest"_** tag. 
Please add the hacktoberfest tag on my pr.

Thanks,
Ayush
